var zmq = require('zmq');

var sequencedRequests = [];
var TOpoint = zmq.socket('router');
var handlerList = ['handler1', 'handler2', 'handler3', 'handler4', 'handler5', 'handler6', 'handler7']; //RELLENAR CUANDO CONOZCAMOS LOS IDS DE LOS HANDLERS
//var auxfunctions = require('./auxfunctions.js');

// ARGUMENTS

var port = 10000;


// Let clients connect to the router:
TOpoint.bindSync('tcp://localhost:' + port);

TOpoint.on('message', function(idHandler, request) {
	// Get the request generated by the client
	var request = JSON.parse(request);

	var position = findIfSequenced(request);
	if (position != -1) {
		broadCastToHandlers(sequencedRequests[position]);
	}
	else {
		request.seq = sequencedRequests.length + 1;
		sequencedRequests.push(request);
		broadCastToHandlers(sequencedRequests[position]);
	}
});

function findIfSequenced(request) {
	if (sequencedRequests.length < 0)
		return -1;
	var i = 0;
	while ((i < sequencedRequests.length) && (sequencedRequests[i].idRequest != request.idRequest)) {
		i = i + 1;
	}
	if (sequencedRequests[i].idRequest == request.idRequest) {
		return i;
	}
	else {
		return -1;
	}
}

function broadCastToHandlers(request) {
	handlerList.forEach(function(handler) {
		TOpoint.send(handler, JSON.stringify(request));
	}) 
}